### ISSUE TITLE
npm run serve does not run (on windows)

### ISSUE THREAD

**Issue by wclr** [cyclejs-community/xstream-boilerplate#12]
**General Problem:**
`npm run serve`:
"serve": "cross-env BABEL_ENV=development babel-node ./node_modules/.bin/webpack-dev-server",
 errors with a like error on Windows: 
![image](https://cloud.githubusercontent.com/assets/736697/15609145/c0dbc988-2437-11e6-8207-d815b6086903.png)

**Comment by TylorS** [comment]
I don't have a windows machine to test this on. Any help on this would be appreciated

**Comment by wclr** [comment]
I searched and it seems that the problem is unsolved on windows (it can not run script from `node_modules/.bin` folder within `node`/`babel-node`)

This can be fixed by replacing with:

1) `cross-env BABEL_ENV=development node -r babel-register -r webpack-dev-server/bin/webpack-dev-server`
or 
2) `cross-env BABEL_ENV=development babel-node ./node_modules/webpack-dev-server/bin/webpack-dev-server`

would you like this fix?

**Comment by TylorS** [comment]
2 looks like a good fix! :+1:
