### ISSUE TITLE
HMR and browserSync

### ISSUE THREAD

**Issue by wclr** [cyclejs-community/xstream-boilerplate#13]
Currenlty configuration of HMR (cycle HMR and webpack HMR) is not correct, due to some mistakes in config (I will fix it) but also due to indlusion of browserSync plugin (it can be used though).

But do you really want to include browserSync in this boilerplate? To me it just a little bit exessive thing for boilerplate and messes things up.

**Comment by TylorS** [comment]
For this is a boilerplate, I really want it to be real-world ready, and not just for simple counter applications. 

BrowserSync seems very useful when you want to test applications on multiple browsers or across multiple devices. However, if it will interfere with the HMR, I'd be in favor of removing it to make sure HMR works, as I think HMR is a more important development tool

**Comment by wclr** [comment]
Ok, actually it seem to work fine, btw there is something wrong with `styles.css` it is not loading

**Comment by TylorS** [comment]
Yeah, I believe its because there is no actual CSS defined yet
