### ISSUE TITLE
Create-cycle-app flavor

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/xstream-boilerplate#233]
As we are working on the create-cycle-app [discovery logic](https://github.com/cyclejs-community/create-cycle-app/pull/8), I was thinking that perhaps this xstream-boilerplate could be converted or made it also available as an installable flavor via the [create-cycle-app](https://github.com/cyclejs-community/create-cycle-app) cli.  

I'm happy to help in this direction if you think that this could bring value to the cycle community.

**Comment by TylorS** [comment]
I won't have the ability to do this for a while, but if there is anything here that you can see as useful feel free to take inspiration. Personally, I'd be happy to deprecate this in favor of `create-cycle-app`, but honestly it's been @FeliciousX who has been maintaining this, so I'll leave that decision to him.

**Comment by FeliciousX** [comment]
I'd be more than happy to help in making this available as a flavor @nickbalestra 
What do we need to do? If it's deprecating this in favour of `create-cycle-app` and working there I don't mind aswell

**Comment by nickbalestra** [comment]
Awesome! I'm currently in the process of rethinking the create-cycle-app discovery mechanism further, ideally relying on the npm registry as a next step. Once that will be done we could make this into a flavor published on npm with a specific keyword and `create-cycle-app` will be able to discover it and use it. Could be a nice example for others willing to create custom flavors. I'll get back in here once the basic create-cycle-app discovery/infrastructure is in place so we can move this further.

**Comment by geovanisouza92** [comment]
FYI, create-cycle-app with discovery is done. This project could be ported now. :tada:

**Comment by nickbalestra** [comment]
Yesss! Started working on this. Will push my work on a branch over the weekend

**Comment by TylorS** [comment]
Good to hear guys :+1:
