### ISSUE TITLE
npm install warnings

### ISSUE THREAD

**Issue by brw31415** [cyclejs-community/xstream-boilerplate#40]
**General Problem:**
node v4.4 npm install warnings
**Minimal Code to reproduce:**

**Expected behavior:**

**Actual behavior:**
@2.15.5 /home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/npm
brw314:~/workspace/xstream (master) $ npm install
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/nightwatch/node_modules/mocha-nightwatch/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/nightwatch/node_modules/mocha-nightwatch/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/nightwatch/node_modules/mocha-nightwatch/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/nightwatch/node_modules/mocha-nightwatch/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/nightwatch/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/ftp requires readable-stream@'1.1.x' but will load
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/nightwatch/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/readable-stream,
npm WARN unmet dependency which is version 2.1.4
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/isparta/node_modules/istanbul/node_modules/handlebars requires source-map@'^0.4.4' but will load
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/isparta/node_modules/source-map,
npm WARN unmet dependency which is version 0.5.6
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/commitizen/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob requires graceful-fs@'~1.2.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/commitizen/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.8
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/commitizen/node_modules/gulp-git/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency /home/ubuntu/workspace/xstream/node_modules/commitizen/node_modules/gulp-git/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
brw314:~/workspace/xstream (master) $ node --version
v4.4.5

**Additional information:**

**Comment by FeliciousX** [comment]
hmm can u try update your node version to v6? @brw31415
